apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-maven
  name: java-maven
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: java-maven
  sessionAffinity: None
  type: ClusterIP
