apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-minimal
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: components/pipelines-as-a-service/minimal
    repoURL: https://github.com/ploigos/openshift-pipelines-quickstart.git
    targetRevision: argo-deploy

  destination:
    namespace: pipelines-minimal
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
