apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nexus
spec:
  host: nexus-sonatype-nexus-service-nexus.apps.cluster-8dsnq.8dsnq.sandbox959.opentlc.com
  port:
    targetPort: application
  to:
    kind: Service
    name: nexus-sonatype-nexus-service
    weight: 100
  wildcardPolicy: None
